<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>dotnet-BNPPIntegration-d5ea4e1b-09dd-4d4b-82b9-5dbad442680f</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="EpicorCustomization\**\*.cs" />
    <None Include="EpicorCustomization\**\*" />
  </ItemGroup>
</Project>
